### ISSUE TITLE
App does not start 

### ISSUE THREAD

**Issue by daslicht** [rethinkdb/rethinkdb-example-nodejs-chat#17]
Hi,
when I clone , npm install , and start the app I get : 

```
AssertionError: RqlDriverError: Server dropped connection with message: "ERROR: The PROTOBUF client protocol is no longer supported"
```

How to fix , Is there somewhere a newer example?

**Comment by mglukhovsky** [comment]
@daslicht: this example was using an outdated version of the RethinkDB driver. I just bumped the version in `package.json`; could you see if it works for you now?

**Comment by floatingFaez** [comment]
hello this clone file dosn't started when i start this app by "node app" it's show me an error that is : E:\Practice\nodetest\nodeChat>node app
module.js:341
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\Practice\nodetest\nodeChat\app.js:15:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

what can i do to solve?

**Comment by daslicht** [comment]
tried npm install bcrypt ?

**Comment by deontologician** [comment]
It's possible the bcrypt module doesn't work on windows, since it'll need a compiler. I don't know for sure though

**Comment by floatingFaez** [comment]
i installed bcrypt, but still i am facing this issue?

**Comment by danielmewes** [comment]
@floatingFaez Are you still seeing the same error? `Error: Cannot find module 'bcrypt'`? That would suggest that bcrypt isn't installed properly yet, or node doesn't find it.
