### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by shawn-dsz** [rethinkdb/rethinkdb-example-nodejs-chat#21]
Just followed the instructions on the readme.

cloned and ran ```npm install ```

running ```node app``` gives: 
```shell
 ✘ shdsouza@L3011  ~/proj/_rethinkdb/rethinkdb-example-nodejs-chat   master  node app
   info  - socket.io started
(node:41118) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
AssertionError: ReqlDriverError: Could not connect to localhost:28015.
connect ECONNREFUSED 127.0.0.1:28015
    at /Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/lib/db.js:36:12
    at tryCatcher (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/shdsouza/proj/_rethinkdb/rethinkdb-example-nodejs-chat/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
 ✘ shdsouza@L3011  ~/proj/_rethinkdb/rethinkdb-example-nodejs-chat   master 
```

**Comment by danielmewes** [comment]
Did you start a RethinkDB server? You'll need to run `rethinkdb` separately.
