### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by elderapo** [rethinkdb/rethinkdb-example-nodejs-chat#23]
I am unable to run this app on Win10 and node v7.3.0. [npm install output](https://gist.github.com/elderapo/3b1c2faa38ab3f2675dd573e35c053d3)
```C:\Users\ziemniak\Documents\GitHub\rethinkdb-example-nodejs-chat>node app
C:\Users\ziemniak\Documents\GitHub\rethinkdb-example-nodejs-chat\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\ziemniak\Documents\GitHub\rethinkdb-example-nodejs-chat\node_modules\socket.io\lib\store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ziemniak\Documents\GitHub\rethinkdb-example-nodejs-chat\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:571:32)```

**Comment by elderapo** [comment]
Actually #22 fixed this issue.
